pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

include ':FtcRobotController'
include ':Team00000'
include ':Team31192'
include ':Team36103'
include ':Team36104'
